# Import .env file natively if it exists
spring.config.import=optional:file:.env[.properties]

# Add your Google Gemini API Key here to enable the Tax Wizard AI
gemini.api.key=${GEMINI_API_KEY}

server.port=8080
server.tomcat.max-http-form-post-size=20MB